spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://k02b2041.p.ssafy.io:3306/newslive?serverTimezone=UTC&characterEncoding=UTF-8
    username: ssafy
    password: ssafy